---

name: cron-tasks

on:
  schedule:
    - cron: '30 3 * * 0'

  workflow_dispatch:

env:
  PYTHON_VERSION: '3.12.x'

permissions:
    actions: read
    contents: read
    issues: read
    pull-requests: read

jobs:
  badge-marketplace: # https://github.com/tagdots/setup-badge-action
      runs-on: ubuntu-latest

      permissions:
        contents: write

      steps:
      - id: marketplace-badge
        uses: tagdots/setup-badge-action@d450907c2ddc3c94b5eaed20f521eb4846475937 # 1.0.4
        with:
          badge-name: marketplace
          badge-url: https://github.com/marketplace/actions/delete-workflow-runs-in-github-action
          label: Marketplace
          message: delete-workflow-runs
          message-color: FF6360

  stale-workflow-runs: # https://github.com/tagdots/delete-workflow-runs-action
    runs-on: ubuntu-latest

    permissions:
      actions: write
      contents: read

    steps:
    - name: Run stale-workflow-runs
      id: stale-workflow-runs
      uses: tagdots/delete-workflow-runs-action@563f02090cdf93da6798bcf304238e8ac383c49e # 1.0.2
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        repo-url: ${{ github.repository }}
        max-days: 10
        dry-run: false

  stale-issues-prs: # https://github.com/actions/stale
    runs-on: ubuntu-latest

    permissions:
      actions: write
      contents: write
      issues: write
      pull-requests: write

    steps:
    - name: Run stale-issues-prs
      id: stale-issues-prs
      uses: actions/stale@5bef64f19d7facfb25b37b414482c7164d639639 # v9.1.0
      with:
        stale-issue-message: 'This issue is stale because it has been open 5 days with no activity. Remove stale label or comment or this will be closed in 3 days after stale'
        days-before-stale: 5
        days-before-close: 3
        operations-per-run: 40

  update-pre-commit: # https://github.com/tagdots/update-pre-commit-action
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
    - name: Run update-pre-commit
      id: update-pre-commit
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: tagdots/update-pre-commit-action@c1b9f2cb98f920a06a99172d09af349bf783f3d9 # 1.0.20
      with:
        file: .pre-commit-config.yaml
        dry-run: false
        open-pr: true

  notify-slack: # https://github.com/slackapi/slack-github-action
    if: always()
    needs: [badge-marketplace, stale-workflow-runs, stale-issues-prs, update-pre-commit]

    runs-on: ubuntu-latest

    outputs:
      WORKFLOW_RESULT: ${{ steps.get-overall-jobs-results.outputs.WORKFLOW_RESULT }}

    steps:
    - name: Get Overall Jobs Results
      id: get-overall-jobs-results
      shell: bash
      run: |
        # get overall result from all of the previous jobs
        if "${{ needs.badge-marketplace.result == 'success' && needs.stale-workflow-runs.result == 'success' && needs.stale-issues-prs.result == 'success' && needs.update-pre-commit.result == 'success' }}"; then
          echo "WORKFLOW_RESULT=:white_check_mark:" >> "$GITHUB_OUTPUT"
        else
          echo "WORKFLOW_RESULT=:no_entry:" >> "$GITHUB_OUTPUT"
        fi

    - name: Post message to Slack
      uses: slackapi/slack-github-action@91efab103c0de0a537f72a35f6b8cda0ee76bf0a # v2.1.1
      with:
        method: chat.postMessage
        token: "${{ secrets.SECRET_SLACK_APP_GITHUB_BOT }}"
        payload: |
          channel: "${{ secrets.SECRET_SLACK_CHANNEL_CRON_TASKS }}"
          text: "
              *Repository: ${{ github.repository }}*\n
              *Workflow : ${{ github.workflow }} ${{ steps.get-overall-jobs-results.outputs.WORKFLOW_RESULT }}*
              ```
              URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}\n
              Job: badge-marketplace   - ${{ needs.badge-marketplace.result }}\n
              Job: stale-workflow-runs - ${{ needs.stale-workflow-runs.result }}\n
              Job: stale-issues-prs    - ${{ needs.stale-issues-prs.result }}\n
              Job: update-pre-commit   - ${{ needs.update-pre-commit.result }}
              ```"
